Repository phingofficial/phing, pull requests merged in 2018-04, with the labels that each got.

#895 Fixed undefined constant.
  classes/phing/tasks/ext/inifile/IniFileTask.php
Labels: defect

#901 Removed obsolete php version check
  classes/phing/system/io/FileParserFactory.php
Labels: core

#900 Fixed condition of child nodes at prefix building in XmlPropertyTask
  classes/phing/tasks/ext/XmlPropertyTask.php
Labels: defect

#899 Fixed nested condition test in FailTask
  classes/phing/tasks/system/FailTask.php
Labels: defect

#898 Fixed PhingFile::createNewFile if parent is null
  classes/phing/system/io/PhingFile.php
Labels: core, defect

#897 Fixed isBoolean check.
  classes/phing/util/StringHelper.php
Labels: core, defect

#902 Fixed #887
  classes/phing/IntrospectionHelper.php
Labels: core, defect

#904 Fixes #560
  classes/phing/types/selectors/ContainsRegexpSelector.php
  classes/phing/types/selectors/ContainsSelector.php
Labels: defect

#905 Take care of PHP return types in IntrospectionHelper
  classes/phing/IntrospectionHelper.php
Labels: core

#903 Made XML based property files loadable.
  classes/phing/system/io/FileParserFactory.php
  classes/phing/system/io/XmlFileParser.php
  classes/phing/tasks/ext/XmlPropertyTask.php
  docs/guide/en/source/appendixes/fileformats.xml
Labels: enhancement

#906 Be less restrictive on TaskContainer::addTask(Task)
  classes/phing/IntrospectionHelper.php
Labels: core

#890 Fix PHP CodeSniffer cache write to directory
  classes/phing/tasks/ext/PhpCodeSnifferTask.php
Labels: defect

#878 Cleanup of #735 - part 1
  classes/phing/tasks/system/ExecTask.php
  classes/phing/types/Environment.php
  classes/phing/types/environment/EnvVariable.php
  docs/guide/en/source/appendixes/coretasks.xml
  etc/phing-grammar.rng
  test/classes/phing/tasks/system/ExecTaskTest.php
  test/etc/tasks/system/ExecTest.xml
Labels: enhancement

#912 Made ProjectConfigurator::__construct private
  classes/phing/parser/ProjectConfigurator.php
Labels: core
