Repository phingofficial/phing, pull requests merged in 2018-06, with the labels that each got.

#932 Added AnsiColorLogger and SilentLogger to the docs
  docs/guide/en/source/appendixes/coreloggers.xml
Labels: documentation

#926 Added nested params to PhpEvalTask
  classes/phing/tasks/system/PhpEvalTask.php
  docs/guide/en/source/appendixes/coretasks.xml
Labels: enhancement

#826 Fix #824: allow the status-code to be checked in http-request task.
  classes/phing/tasks/ext/HttpRequestTask.php
Labels: enhancement

#935 Fixed test execution.
  classes/phing/filters/XsltFilter.php
Labels: defect

#937 Fixed DefaultExcludes by removing an old hhvm fix
  classes/phing/util/DirectoryScanner.php
Labels: defect

#938 Cleanup of #735 - part 2
  classes/phing/types/CommandlineMarker.php
Labels: enhancement

#939 Cleanup of #735 - part 3
  classes/phing/util/DirectoryScanner.php
Labels: enhancement
