Repository phingofficial/phing, pull requests merged in 2018-10, with the labels that each got.

#968 Fixed null pointer exception
  test/classes/phing/BuildFileTest.php
Labels: defect

#969 Added preserve duplicates to PathConvert
  classes/phing/tasks/system/PathConvert.php
  classes/phing/types/Path.php
  docs/guide/en/source/appendixes/coretasks.xml
  etc/phing-grammar.rng
  test/classes/phing/tasks/system/PathConvertTest.php
Labels: enhancement

#972 Avoid calling get_class on null in UnknownElement.
  classes/phing/UnknownElement.php
Labels: defect

#963 Added index to foreach task
  classes/phing/tasks/system/ForeachTask.php
  composer.lock
  docs/guide/en/source/appendixes/coretasks.xml
  etc/phing-grammar.rng
  test/classes/phing/tasks/system/ForeachTaskTest.php
  test/etc/tasks/system/ForeachTaskTest.xml
Labels: enhancement

#975 Removed outdated todo
  classes/phing/filters/StripWhitespace.php
Labels: core
