Repository phingofficial/phing, pull requests merged in 2019-11, with the labels that each got.

#1176 Parameter unittests
  test/classes/phing/types/ParameterTest.php
Labels: added tests, core

#1183 Fixed indention
  appveyor.yml
  classes/phing/tasks/system/UpToDateTask.php
  composer.lock
Labels: cleanup, core, scrutinizer

#1189 Removed unused lines of code.
  classes/phing/types/FileList.php
Labels: cleanup, core

#1190 [FileList] Fixed iterator
  classes/phing/types/FileList.php
Labels: core, defect

#1191 replace @expectedException* anotation
  test/classes/phing/system/condition/VersionCompareConditionTest.php
  test/classes/phing/system/io/IniFileParserTest.php
  test/classes/phing/system/io/YamlFileParserTest.php
  test/classes/phing/system/lang/EventObjectTest.php
  test/classes/phing/tasks/PropertyTaskTest.php
  test/classes/phing/tasks/TaskdefTaskTest.php
  test/classes/phing/tasks/TypedefTaskTest.php
  test/classes/phing/tasks/ext/GrowlNotifyTaskTest.php
  test/classes/phing/tasks/ext/HTTP/BaseHttpTaskTest.php
  test/classes/phing/tasks/ext/HTTP/HttpGetTaskTest.php
  test/classes/phing/tasks/ext/HTTP/HttpRequestTaskTest.php
  test/classes/phing/tasks/ext/PHPStanTask/Acceptance/PHPStanTaskTest.php
  test/classes/phing/tasks/ext/PHPStanTask/Unit/CommandBuilder/PHPStanCommandBuilderFactoryTest.php
  test/classes/phing/tasks/ext/PHPStanTask/Unit/CommandBuilder/PHPStanCommandBuilderTest.php
  test/classes/phing/tasks/ext/SassTask/Acceptance/SassTaskAcceptanceTest.php
  test/classes/phing/tasks/ext/SassTask/Integration/SassCompilerTest.php
  test/classes/phing/tasks/ext/SassTask/Integration/ScssPhpCompilerTest.php
  test/classes/phing/tasks/ext/SassTask/Unit/SassTaskCompilerFactoryTest.php
  test/classes/phing/tasks/ext/inifile/IniFileTaskTest.php
  test/classes/phing/tasks/ext/rST/RSTTaskMultipleMappersTest.php
  test/classes/phing/tasks/ext/rST/RSTTaskTest.php
  test/classes/phing/tasks/ext/sonar/SonarConfigurationFileParserTest.php
  test/classes/phing/tasks/system/AppendTaskTest.php
  test/classes/phing/tasks/system/BlockForTaskTest.php
  test/classes/phing/tasks/system/ExecTaskTest.php
  test/classes/phing/tasks/system/ForeachTaskTest.php
  test/classes/phing/tasks/system/RelentlessTest.php
  test/classes/phing/tasks/system/RetryTest.php
  test/classes/phing/tasks/system/TouchTaskTest.php
  test/classes/phing/tasks/system/TruncateTaskTest.php
  test/classes/phing/types/CommandlineTest.php
  test/classes/phing/types/DataTypeTest.php
  test/classes/phing/types/EnvironmentTest.php
  test/classes/phing/types/PatternSetTest.php
  test/classes/phing/types/PearPackageFileSetTest.php
  test/classes/phing/types/ReferenceTest.php
  test/classes/phing/util/DirectoryScannerTest.php
  test/classes/phing/util/PearPackageScannerTest.php
Labels: cleanup, core

#1193 replace ignore-checks in tests
  .gitignore
  test/classes/phing/PhingTest.php
  test/classes/phing/regression/ExcludeZipTest.php
  test/classes/phing/regression/PearPkg2CompatibilityTest.php
  test/classes/phing/system/condition/SocketConditionTest.php
  test/classes/phing/system/io/AbstractWinFileSystemTestCase.php
  test/classes/phing/system/io/WindowsFileSystemTest.php
  test/classes/phing/tasks/ext/DbDeployTaskTest.php
  test/classes/phing/tasks/ext/PHPLOCTaskTest.php
  test/classes/phing/tasks/ext/PearPackageTest.php
  test/classes/phing/tasks/ext/PharDataTaskTest.php
  test/classes/phing/tasks/ext/PharPackageTaskTest.php
  test/classes/phing/tasks/ext/PhpCodeSnifferTaskTest.php
  test/classes/phing/tasks/ext/PhpLintTaskTest.php
  test/classes/phing/tasks/ext/VisualizerTaskTest.php
  test/classes/phing/tasks/ext/ZipUnzipTaskTest.php
  test/classes/phing/tasks/ext/property/VariableTest.php
  test/classes/phing/tasks/ext/rST/RSTTaskTest.php
  test/classes/phing/tasks/system/ApplyTaskTest.php
  test/classes/phing/tasks/system/AttribTaskTest.php
  test/classes/phing/tasks/system/ChmodTaskTest.php
  test/classes/phing/tasks/system/ChownTaskTest.php
  test/classes/phing/tasks/system/ConditionTaskTest.php
  test/classes/phing/tasks/system/CopyTaskTest.php
  test/classes/phing/tasks/system/DefaultExcludesTest.php
  test/classes/phing/tasks/system/DeleteTaskTest.php
  test/classes/phing/tasks/system/ExecTaskTest.php
  test/classes/phing/tasks/system/RelentlessTest.php
  test/classes/phing/tasks/system/XsltTaskTest.php
  test/classes/phing/types/PearPackageFileSetBuildTest.php
  test/classes/phing/types/PearPackageFileSetTest.php
  test/classes/phing/util/PearPackageScannerTest.php
Labels: core
