Repository phingofficial/phing, pull requests merged in 2019-08, with the labels that each got.

#1096 [phpcs] phpcs 3 compatible task
  classes/phing/tasks/defaults.properties
  classes/phing/tasks/ext/PhpCSTask.php
  classes/phing/tasks/ext/phpunit/PHPUnitTask.php
  composer.json
  composer.lock
  docs/guide/en/source/appendixes/optionaltasks.xml
  etc/phing-grammar.rng
  ruleset.xml
  test/build.xml
  test/classes/phing/tasks/ext/PhpCSTaskTest.php
  test/etc/tasks/ext/phpcs/build.xml
Labels: enhancement, ext tasks

#1106 Only send coverage report if not phpcs build
  .travis.yml
Labels: core

#1107 Updated scrutinizer config
  .scrutinizer.yml
Labels: core

#1108 IntrospectionHelper should not convert to bool, if a typehinted string was found.
  classes/phing/IntrospectionHelper.php
  classes/phing/tasks/system/PropertyTask.php
  classes/phing/types/CommandlineArgument.php
Labels: core, defect

#1109 Fixed scrutinizer issue
  classes/phing/Project.php
Labels: scrutinizer

#1110 Fixed some more ci issues.
  classes/phing/filters/BaseParamFilterReader.php
  classes/phing/filters/ChainableReader.php
  classes/phing/filters/ConcatFilter.php
  classes/phing/filters/EscapeUnicode.php
  classes/phing/filters/ExpandProperties.php
  classes/phing/filters/HeadFilter.php
  classes/phing/filters/IconvFilter.php
  classes/phing/filters/LineContains.php
  classes/phing/filters/LineContainsRegexp.php
  classes/phing/filters/PhpArrayMapLines.php
  classes/phing/filters/PrefixLines.php
  classes/phing/filters/ReplaceRegexp.php
  classes/phing/filters/ReplaceTokens.php
  classes/phing/filters/ReplaceTokensWithFile.php
  classes/phing/filters/SortFilter.php
  classes/phing/filters/StripLineBreaks.php
  classes/phing/filters/StripLineComments.php
  classes/phing/filters/StripPhpComments.php
  classes/phing/filters/StripWhitespace.php
  classes/phing/filters/SuffixLines.php
  classes/phing/filters/TabToSpaces.php
  classes/phing/filters/TailFilter.php
  classes/phing/filters/TidyFilter.php
  classes/phing/filters/TranslateGettext.php
  classes/phing/filters/XincludeFilter.php
  classes/phing/filters/XsltFilter.php
  classes/phing/types/Parameterizable.php
  classes/phing/types/selectors/BaseExtendSelector.php
  classes/phing/types/selectors/ContainsRegexpSelector.php
  classes/phing/types/selectors/ContainsSelector.php
  classes/phing/types/selectors/DateSelector.php
  classes/phing/types/selectors/DepthSelector.php
  classes/phing/types/selectors/FilenameSelector.php
  classes/phing/types/selectors/SizeSelector.php
  classes/phing/types/selectors/TypeSelector.php
Labels: cleanup, core, scrutinizer

#1111 Fixed some more inspections
  classes/phing/BuildEvent.php
  classes/phing/FileScanner.php
  classes/phing/Phing.php
  classes/phing/Project.php
  classes/phing/PropertyHelper.php
  classes/phing/Target.php
  classes/phing/UnknownElement.php
  classes/phing/filters/ExpandProperties.php
  classes/phing/filters/IconvFilter.php
  classes/phing/filters/ReplaceRegexp.php
  classes/phing/filters/SortFilter.php
  classes/phing/filters/StripLineBreaks.php
  classes/phing/filters/StripPhpComments.php
  classes/phing/filters/TabToSpaces.php
  classes/phing/filters/XincludeFilter.php
  classes/phing/parser/AbstractHandler.php
  classes/phing/system/io/WindowsFileSystem.php
  classes/phing/system/util/Properties.php
  classes/phing/tasks/ext/FtpDeployTask.php
  classes/phing/tasks/ext/PearPackage2Task.php
  classes/phing/tasks/ext/PhpLintTask.php
  classes/phing/tasks/ext/Service/Amazon/S3/S3PutTask.php
  classes/phing/tasks/ext/coverage/CoverageReportTask.php
  classes/phing/tasks/ext/dbdeploy/DbDeployTask.php
  classes/phing/tasks/ext/git/GitArchiveTask.php
  classes/phing/tasks/ext/git/GitBaseTask.php
  classes/phing/tasks/ext/phpunit/PHPUnitUtil.php
  classes/phing/tasks/ext/phpunit/formatter5/PHPUnitResultFormatter5.php
  classes/phing/tasks/ext/phpunit/formatter6/PHPUnitResultFormatter6.php
  classes/phing/tasks/ext/phpunit/formatter7/PHPUnitResultFormatter7.php
  classes/phing/tasks/ext/ssh/ScpTask.php
  classes/phing/tasks/ext/zendguard/ZendGuardLicenseTask.php
  classes/phing/tasks/system/EchoProperties.php
  classes/phing/tasks/system/RecorderTask.php
  classes/phing/tasks/system/TruncateTask.php
  classes/phing/tasks/system/UpToDateTask.php
  classes/phing/types/CommandlineMarker.php
  classes/phing/types/PhingFilterReader.php
Labels: cleanup, core, scrutinizer

#1105 Added iterator support for FileList
  classes/phing/types/FileList.php
Labels: core

#1115 Fixed low deps issue
  test/classes/phing/PhingTest.php
  test/classes/phing/tasks/ext/sonar/SonarConfigurationFileParserTest.php
  test/classes/phing/types/PearPackageFileSetTest.php
Labels: core, defect

#1114 Added circular reference check.
  classes/phing/types/AbstractFileSet.php
Labels: core

#1116 Fixed some inspections
  classes/phing/tasks/ext/coverage/CoverageReportTask.php
Labels: cleanup, core

#1118 Reduced copy paste
  classes/phing/tasks/system/RecorderEntry.php
Labels: cleanup, core

#1119 Get rid of useless code in PhingFile
  classes/phing/system/io/PhingFile.php
Labels: cleanup, core

#1120 Added verbose log to mkdir if dir exists already.
  classes/phing/tasks/system/MkdirTask.php
Labels: core, enhancement

#1121 database condition
  appveyor.yml
  classes/phing/tasks/ext/pdo/PDOSQLExecTask.php
  classes/phing/tasks/system/condition/ConditionBase.php
  docs/guide/en/source/appendixes/optionaltasks.xml
  docs/guide/en/source/chapters/gettingstarted.xml
  docs/guide/en/source/chapters/projcomponents.xml
  etc/phing-grammar.rng
  test/classes/phing/tasks/condition/PDOSQLExecTaskConditionTest.php
  test/etc/tasks/ext/PDOSQLExecTaskConditionTest.xml
Labels: enhancement, ext tasks

#1122 Code cleanup
  classes/phing/tasks/ext/pdo/PDOSQLExecTask.php
Labels: cleanup
