Repository phingofficial/phing, pull requests merged in 2019-12, with the labels that each got.

#1195 Updated dependencies
  .travis.yml
  classes/phing/tasks/ext/phpunit/PHPUnitTestRunner8.php
  composer.json
  composer.lock
  test/classes/phing/PhingTest.php
  test/classes/phing/regression/PearPkg2CompatibilityTest.php
  test/classes/phing/system/lang/CharacterTest.php
  test/classes/phing/tasks/ext/FileHashTaskTest.php
  test/classes/phing/tasks/ext/PDO/PDODelimitersTest.php
  test/classes/phing/tasks/ext/PHPCPDTaskTest.php
  test/classes/phing/tasks/ext/PearPackageTest.php
  test/classes/phing/tasks/ext/PhpCodeSnifferTaskTest.php
  test/classes/phing/tasks/ext/WikiPublishTaskTest.php
  test/classes/phing/tasks/ext/rST/RSTTaskTest.php
  test/classes/phing/tasks/ext/sonar/SonarConfigurationFileParserTest.php
  test/classes/phing/tasks/system/AppendTaskTest.php
  test/classes/phing/tasks/system/ExecTaskTest.php
Labels: core, dependencies

#1204 Monolog listener
  classes/phing/listener/MonologListener.php
  composer.json
  composer.lock
  docs/guide/en/source/appendixes/coreloggers.xml
  test/classes/phing/listener/MonologListenerTest.php
Labels: enhancement

#1208 Added multi line description support, …
  classes/phing/Phing.php
  classes/phing/Project.php
  classes/phing/RuntimeConfigurable.php
  classes/phing/Target.php
  classes/phing/Task.php
  classes/phing/types/Description.php
  etc/phing-grammar.rng
  test/classes/phing/PhingTest.php
  test/classes/phing/types/DescriptionTest.php
  test/etc/types/description1.xml
  test/etc/types/description2.xml
  test/etc/types/description3.xml
  test/etc/types/description4.xml
Labels: added tests, core, enhancement

#1216 Removed memory limit from travis ini and some refactor
  .travis.php.ini
  .travis.yml
  test/phpunit.xml
Labels: cleanup, core

#1217 [EchoTask] Fixed type handling.
  classes/phing/tasks/system/EchoTask.php
Labels: defect

#1218 [PropertyTask] Added type hints
  classes/phing/tasks/system/PropertyTask.php
Labels: defect

#1215 [patch for 2.16.2][php7] Deprecated: Array and string offset access syntax with curly braces is deprecated
  .travis.yml
  classes/phing/Phing.php
  classes/phing/system/io/BufferedReader.php
  classes/phing/system/io/UnixFileSystem.php
  classes/phing/tasks/ext/git/GitBranchTask.php
  classes/phing/tasks/ext/git/GitCheckoutTask.php
  classes/phing/types/Path.php
  classes/phing/util/FileUtils.php
  classes/phing/util/PathTokenizer.php
  classes/phing/util/StringHelper.php
  docs/docbook5/en/output/chunkhtml/GitBranchTask.html
  docs/docbook5/en/output/hlhtml/index.html
  docs/docbook5/en/source/appendixes/optionaltasks.xml
  test/classes/phing/tasks/ext/GitTasks/GitBranchTaskTest.php
  test/classes/phing/tasks/ext/GitTasks/GitMergeTaskTest.php
  test/etc/tasks/ext/git/GitBranchTaskTest.xml
Labels: PHP compat, core

#1221 Fixed IsTrueCondition
  classes/phing/tasks/system/condition/IsTrueCondition.php
Labels: defect

#1209 Added posix permission selector
  classes/phing/tasks/ext/phpunit/PHPUnitTestRunner7.php
  classes/phing/tasks/ext/phpunit/PHPUnitTestRunner8.php
  classes/phing/types/selectors/PosixPermissionsSelector.php
  classes/phing/types/selectors/SelectorAware.php
  docs/guide/en/source/appendixes/selectors.xml
  etc/phing-grammar.rng
  test/classes/phing/types/selectors/PosixPermissionsSelectorTest.php
Labels: enhancement

#1226 [PropertyTask] Added "required" attribute
  classes/phing/tasks/ext/XmlPropertyTask.php
  classes/phing/tasks/system/PropertyTask.php
  docs/guide/en/source/appendixes/coretasks.xml
  etc/phing-grammar.rng
  test/classes/phing/tasks/PropertyTaskTest.php
  test/etc/tasks/property.xml
Labels: enhancement
