Repository phingofficial/phing, pull requests merged in 2019-10, with the labels that each got.

#1141 StringReader should be an InputStreamReader
  classes/phing/system/io/StringReader.php
Labels: core, defect

#1143 Rename __import method
  classes/phing/Phing.php
  classes/phing/tasks/ext/phpunit/PHPUnitUtil.php
Labels: cleanup, core

#1136 add Build-Matrix
  .travis.yml
Labels: core, enhancement

#1144 The variable '$php_errormsg' is deprecated since PHP 7.2; Using error_get_last() instead
  classes/phing/system/io/FileOutputStream.php
  classes/phing/system/io/FileSystem.php
  classes/phing/system/io/InputStream.php
  classes/phing/system/io/OutputStream.php
  classes/phing/system/io/UnixFileSystem.php
Labels: core

#1145 [StatisticsListener] Fixed PHP Error
  classes/phing/listener/statistics/TimerMap.php
Labels: defect

#1146 Datatype unit-tests
  test/classes/phing/types/DataTypeTest.php
Labels: core

#1147 [DataTypeTest] Added missing license and property
  test/classes/phing/types/DataTypeTest.php
Labels: cleanup, core

#1148 Fixed notice in JsonLogger.
  classes/phing/listener/XmlLogger.php
Labels: cleanup, core, scrutinizer

#1149 [PhingTest] Added test case for printUsage
  test/classes/phing/PhingTest.php
Labels: core, scrutinizer

#1150 Added bootstrap to scrutinizer config
  .scrutinizer.yml
Labels: core, scrutinizer

#1152 Fixed PSR12 related errors by phpcbf
  classes/phing/IntrospectionHelper.php
  classes/phing/Phing.php
  classes/phing/listener/DefaultLogger.php
  classes/phing/listener/NoBannerLogger.php
  classes/phing/mappers/GlobMapper.php
  classes/phing/parser/PhingXMLContext.php
  classes/phing/parser/TargetHandler.php
  classes/phing/system/io/WindowsFileSystem.php
  classes/phing/tasks/ext/ExtractBaseTask.php
  classes/phing/tasks/ext/FileHashTask.php
  classes/phing/tasks/ext/FileSizeTask.php
  classes/phing/tasks/ext/HttpGetTask.php
  classes/phing/tasks/ext/PhpCodeSnifferTask.php
  classes/phing/tasks/ext/PhpLintTask.php
  classes/phing/tasks/ext/RSTTask.php
  classes/phing/tasks/ext/coverage/CoverageThresholdTask.php
  classes/phing/tasks/ext/hg/HgAddTask.php
  classes/phing/tasks/ext/inifile/IniFileConfig.php
  classes/phing/tasks/ext/pdo/DefaultPDOQuerySplitter.php
  classes/phing/tasks/ext/pdo/DummyPDOQuerySplitter.php
  classes/phing/tasks/ext/pdo/PDOSQLExecTask.php
  classes/phing/tasks/ext/phpcpd/PHPCPDTask.php
  classes/phing/tasks/ext/phpmd/PHPMDRendererRemoveFromCache.php
  classes/phing/tasks/ext/phpunit/PHPUnitTask.php
  classes/phing/tasks/ext/sass/SassTask.php
  classes/phing/tasks/ext/visualizer/VisualizerTask.php
  classes/phing/tasks/system/AppendTask.php
  classes/phing/tasks/system/ApplyTask.php
  classes/phing/tasks/system/CopyTask.php
  classes/phing/tasks/system/DeleteTask.php
  classes/phing/tasks/system/DependSet.php
  classes/phing/tasks/system/ImportTask.php
  classes/phing/tasks/system/MoveTask.php
  classes/phing/tasks/system/PhingTask.php
  classes/phing/tasks/system/TaskdefTask.php
  classes/phing/types/Commandline.php
  classes/phing/types/selectors/SelectorUtils.php
  classes/phing/util/FileUtils.php
  classes/phing/util/PathTokenizer.php
  composer.json
  composer.lock
  ruleset.xml
Labels: scrutinizer

#1153 Added SleepTaskTest
  test/classes/phing/tasks/system/SleepTaskTest.php
  test/etc/tasks/system/SleepTaskTest.xml
Labels: core

#1151 Add unit test for Description addText method
  test/classes/phing/types/DescriptionTest.php
Labels: core

#1164 [DefaultLogger] added unit test for buildFinished
  classes/phing/listener/DefaultLogger.php
  test/classes/phing/listener/DefaultLoggerTest.php
Labels: core

#1161 PSR12 and Object Calisthenics
  classes/phing/listener/DefaultLogger.php
Labels: cleanup, core

#1165 Added test for StatisticsListener
  classes/phing/listener/statistics/StatisticsReport.php
  test/classes/phing/listener/StatisticsListenerTest.php
Labels: core

#1166 Create TimestampedLoggerTest
  test/classes/phing/listener/TimestampedLoggerTest
Labels: core

#1167 Added SilentLoggerTest
  test/classes/phing/listener/SilentLoggerTest.php
  test/classes/phing/listener/TimestampedLoggerTest.php
Labels: core

#1168 Added PrefixLines test
  classes/phing/filters/BaseFilterReader.php
  classes/phing/filters/PrefixLines.php
  test/classes/phing/filters/PrefixLinesTest.php
  test/etc/filters/input/prefixlines.test
  test/etc/filters/prefixlines.xml
Labels: core

#1135 FileHashTask should always generate a file.
  build/build.xml
  classes/phing/tasks/ext/FileHashTask.php
  docs/guide/en/source/appendixes/optionaltasks.xml
  test/classes/phing/tasks/ext/FileHashTaskTest.php
Labels: enhancement

#1177 Fixed not called Phing::shutdown()
  bin/phing.php
  classes/phing/Phing.php
Labels: core, defect

#1178 Move from PhingFile to SplFileObject - part 1
  classes/phing/Diagnostics.php
  classes/phing/Phing.php
  classes/phing/filters/StripWhitespace.php
  classes/phing/mappers/CutDirsMapper.php
  classes/phing/parser/ExpatParser.php
  classes/phing/system/io/FileSystem.php
  classes/phing/system/io/PhingFile.php
  classes/phing/system/io/UnixFileSystem.php
  classes/phing/system/io/WindowsFileSystem.php
  classes/phing/tasks/ext/RSTTask.php
  classes/phing/tasks/ext/WikiPublishTask.php
  classes/phing/tasks/ext/property/PathToFileSet.php
  classes/phing/tasks/ext/zendguard/ZendGuardLicenseTask.php
  classes/phing/tasks/system/ApplyTask.php
  classes/phing/tasks/system/PathConvert.php
  classes/phing/types/Commandline.php
  classes/phing/util/DirectoryScanner.php
  classes/phing/util/FileUtils.php
  test/classes/phing/filters/StripWhitespaceTest.php
  test/classes/phing/system/io/YamlFileParserTest.php
  test/classes/phing/tasks/system/ApplyTaskTest.php
  test/classes/phing/tasks/system/ExecTaskTest.php
  test/classes/phing/types/selectors/SelectorUtilsTest.php
  test/etc/filters/input/stripwhitespace.test
  test/etc/filters/stripwhitespace.xml
Labels: cleanup, core
