Repository phingofficial/phing, pull requests merged in 2019-07, with the labels that each got.

#1079 [StopWatch] Fixed visibility of action methods.
  classes/phing/tasks/ext/StopwatchTask.php
Labels: defect

#1089 [HttpCondition] Removed deprecated constant php 7.3 compat
  classes/phing/tasks/system/condition/HttpCondition.php
Labels: defect

#1084 Feature/visualizer theming
  classes/phing/tasks/ext/visualizer/calls.xsl
  classes/phing/tasks/ext/visualizer/header.xsl
  test/classes/phing/tasks/ext/VisualizerTaskTest.php
  test/etc/tasks/ext/visualizer/VisualizerTaskTest.xml
Labels: enhancement

#1090 Reduced code
  classes/phing/tasks/system/ExecTask.php
  classes/phing/tasks/system/element/LogLevelAware.php
Labels: cleanup, core

#1091 PHPStanTask with Fileset support
  classes/phing/tasks/ext/phpstan/CommandBuilder/PHPStanAnalyseCommandBuilder.php
  classes/phing/tasks/ext/phpstan/CommandBuilder/PHPStanCommandBuilder.php
  classes/phing/tasks/ext/phpstan/CommandBuilder/PHPStanHelpCommandBuilder.php
  classes/phing/tasks/ext/phpstan/CommandBuilder/PHPStanListCommandBuilder.php
  classes/phing/tasks/ext/phpstan/PHPStanTask.php
  docs/guide/en/source/appendixes/optionaltasks.xml
  etc/phing-grammar.rng
  test/classes/phing/tasks/ext/PHPStanTask/Acceptance/PHPStanTaskTest.php
  test/classes/phing/tasks/ext/PHPStanTask/Unit/CommandBuilder/PHPStanAnalyseCommandBuilderTest.php
  test/classes/phing/tasks/ext/PHPStanTask/Unit/CommandBuilder/PHPStanCommandBuilderTest.php
  test/classes/phing/tasks/ext/PHPStanTask/Unit/CommandBuilder/PHPStanHelpCommandBuilderTest.php
  test/classes/phing/tasks/ext/PHPStanTask/Unit/CommandBuilder/PHPStanListCommandBuilderTest.php
  test/etc/tasks/ext/phpstan/PHPStanTaskTest.xml
Labels: enhancement

#1097 PSR-12
  classes/phing/IntrospectionHelper.php
  classes/phing/Target.php
  classes/phing/filters/BaseFilterReader.php
  classes/phing/filters/StripWhitespace.php
  classes/phing/filters/XincludeFilter.php
  classes/phing/filters/XsltFilter.php
  classes/phing/system/io/FileSystem.php
  classes/phing/system/io/PhingFile.php
  classes/phing/system/io/YamlFileParser.php
  classes/phing/tasks/ext/PatchTask.php
  classes/phing/tasks/ext/RSTTask.php
  classes/phing/tasks/ext/SmartyTask.php
  classes/phing/tasks/ext/TarFileSet.php
  classes/phing/tasks/ext/TarTask.php
  classes/phing/tasks/ext/XmlLintTask.php
  classes/phing/tasks/ext/ZipTask.php
  classes/phing/tasks/ext/coverage/CoverageReportTransformer.php
  classes/phing/tasks/ext/git/GitLogTask.php
  classes/phing/tasks/ext/git/GitMergeTask.php
  classes/phing/tasks/ext/git/GitPullTask.php
  classes/phing/tasks/ext/git/GitPushTask.php
  classes/phing/tasks/ext/inifile/IniFileTask.php
  classes/phing/tasks/ext/pdo/PDOSQLExecFormatterElement.php
  classes/phing/tasks/ext/pdo/XMLPDOResultFormatter.php
  classes/phing/tasks/ext/phpunit/PHPUnitReportTask.php
  classes/phing/tasks/ext/phpunit/PHPUnitTask.php
  classes/phing/tasks/ext/phpunit/formatter5/CloverPHPUnitResultFormatter5.php
  classes/phing/tasks/ext/phpunit/formatter6/CloverPHPUnitResultFormatter6.php
  classes/phing/tasks/ext/phpunit/formatter7/CloverPHPUnitResultFormatter7.php
  classes/phing/tasks/ext/sonar/SonarConfigurationFileParser.php
  classes/phing/tasks/ext/ssh/SshTask.php
  classes/phing/tasks/ext/svn/SvnProplistTask.php
  classes/phing/tasks/system/ApplyTask.php
  classes/phing/tasks/system/CopyTask.php
  classes/phing/tasks/system/DeleteTask.php
  classes/phing/tasks/system/MatchingTask.php
  classes/phing/tasks/system/PhingCallTask.php
  classes/phing/tasks/system/PhingTask.php
  classes/phing/tasks/system/PropertyTask.php
  classes/phing/tasks/system/TempFile.php
  classes/phing/tasks/system/condition/ContainsCondition.php
  classes/phing/tasks/system/condition/EqualsCondition.php
  classes/phing/tasks/system/condition/FilesMatch.php
  classes/phing/types/PatternSet.php
  classes/phing/types/selectors/DateSelector.php
  classes/phing/util/StringHelper.php
  classes/phing/util/regexp/PregEngine.php
Labels: cleanup
