Repository phingofficial/phing, pull requests merged in 2019-02, with the labels that each got.

#1019 Feature/visualizer task
  classes/phing/tasks/defaults.properties
  classes/phing/tasks/ext/visualizer/VisualizerTask.php
  classes/phing/tasks/ext/visualizer/calls.xsl
  classes/phing/tasks/ext/visualizer/footer.xsl
  classes/phing/tasks/ext/visualizer/header.xsl
  classes/phing/tasks/ext/visualizer/targets.xsl
  composer.json
  composer.lock
  docs/guide/en/source/appendixes/coretasks.xml
  docs/guide/en/source/appendixes/optionaltasks.xml
  docs/guide/en/source/chapters/projcomponents.xml
  etc/phing-grammar.rng
  test/classes/phing/BuildFileTest.php
  test/classes/phing/tasks/ext/VisualizerTaskTest.php
  test/etc/tasks/ext/visualizer/.gitignore
  test/etc/tasks/ext/visualizer/VisualizerTaskTest.xml
  test/etc/tasks/ext/visualizer/build.xml
  test/etc/tasks/ext/visualizer/import1.xml
  test/etc/tasks/ext/visualizer/import2.xml
Labels: enhancement

#1028 Added test cases.
  classes/phing/Phing.php
  test/classes/phing/IntrospectionHelperTest.php
  test/classes/phing/PhingTest.php
  test/classes/phing/system/lang/CharacterTest.php
  test/classes/phing/system/lang/EventObjectTest.php
  test/classes/phing/system/util/TimerTest.php
Labels: core

#1027 Fixed single test execution of phpunit tests.
  test/phpunit.xml
Labels: defect

#1029 Improved debug log - ref to string if possible
  classes/phing/Project.php
  classes/phing/types/PropertyValue.php
Labels: core
