Repository phingofficial/phing, pull requests merged in 2019-09, with the labels that each got.

#1130 add editorconfig, update gitattributes
  .editorconfig
  .gitattributes
  .gitignore
  test/build.xml
Labels: enhancement

#1131 Added ext-intl to appveyor.yml
  appveyor.yml
Labels: core

#1132 update dependencies
  composer.json
  composer.lock
Labels: core

#1133 Removed duplicated code.
  classes/phing/tasks/system/ResolvePathTask.php
Labels: cleanup, core

#1134 Added loglevel attribute to the phpcs task.
  classes/phing/tasks/ext/PhpCSTask.php
  classes/phing/tasks/system/element/LogLevelAware.php
  docs/guide/en/source/appendixes/optionaltasks.xml
  etc/phing-grammar.rng
  test/etc/tasks/ext/phpcs/build.xml
Labels: enhancement
