Repository phingofficial/phing, pull requests merged in 2020-09, with the labels that each got.

#1386 Downgraded guzzle to 6.5
  composer.json
  composer.lock
Labels: defect

#1389 [HttpRequest] Fixed verbose mode.
  classes/phing/tasks/ext/HttpRequestTask.php
Labels: defect

#1390 Fix visualizer bug
  classes/phing/tasks/ext/HttpTask.php
  classes/phing/tasks/ext/visualizer/VisualizerTask.php
Labels: defect, ext tasks

#1393 Variable properties which could not expanded should be null.
  classes/phing/PropertyHelper.php
  classes/phing/tasks/ext/HttpGetTask.php
  classes/phing/tasks/ext/HttpTask.php
  test/classes/phing/tasks/ext/HTTP/HttpGetTaskTest.php
  test/etc/tasks/ext/http/httpget.xml
Labels: core, defect
