Repository phingofficial/phing, pull requests merged in 2020-12, with the labels that each got.

#1469 Updated Dependencies
  .travis.cov.php.ini
  .travis.yml
  composer.lock
Labels: dependencies

#1470 [core] Move internal build steps from travis to github
  .gitattributes
  .github/workflows/build.yml
  .travis.cov.php.ini
  .travis.php.ini
  .travis.yml
  appveyor.yml
  build/build.xml
  build/manifest.xml
  composer.json
  composer.lock
  test/classes/phing/filters/util/StripPhpCommentsTest.php
  test/classes/phing/tasks/ext/sonar/SonarTaskTest.php
Labels: core

#1471 [core] Fixed delta in TimerTest.php
  test/classes/phing/system/util/TimerTest.php
Labels: core

#1456 Add tests and correct TouchTask behavior
  classes/phing/tasks/system/TouchTask.php
  test/classes/phing/tasks/system/TouchTaskTest.php
  test/etc/tasks/system/TouchTaskTest.xml
  test/etc/types/selectors/DifferentSelectorTest.xml
Labels: added tests, defect, system tasks

#1473 [DateSelector] Add tests and correct behavior
  classes/phing/types/selectors/DateSelector.php
  test/classes/phing/types/selectors/DateSelectorTest.php
  test/etc/types/selectors/DateSelectorTest.xml
Labels: added tests, cleanup, defect

#1474 Changed build trigger handling
  .github/workflows/build.yml
Labels: core

#1476 [BindTargets] Added BindTargets Task
  .github/workflows/build.yml
  classes/phing/tasks/defaults.properties
  classes/phing/tasks/system/BindTargets.php
  etc/phing-grammar.rng
  test/classes/phing/tasks/system/BindTargetsTest.php
  test/etc/tasks/system/BindTargets.xml
Labels: enhancement, system tasks

#1477 Show suggestion on unknown target
  .github/workflows/build.yml
  classes/phing/Project.php
Labels: core, enhancement

#1481 [PatternSet] Simplified __toString method.
  classes/phing/types/PatternSet.php
Labels: cleanup, core

#1484 [phploc] Fixed test case.
  test/etc/tasks/ext/phploc/build.xml
Labels: defect, ext tasks

#1485 [Pear*] Removed unused test xml file.
  test/etc/types/PearPackageFileSetBuildTest.xml
Labels: cleanup

#1486 [PHPUnitTask] Removed PHPUnitTestRunner7
  classes/phing/tasks/ext/phpunit/PHPUnitTask.php
  classes/phing/tasks/ext/phpunit/PHPUnitTestRunner7.php
Labels: cleanup, ext tasks

#1487 Added ModifiedSelector.
  classes/phing/tasks/system/MatchingTask.php
  classes/phing/types/defaults.properties
  classes/phing/types/selectors/SelectorAware.php
  classes/phing/types/selectors/SelectorContainer.php
  classes/phing/types/selectors/modifiedselector/Algorithm.php
  classes/phing/types/selectors/modifiedselector/Cache.php
  classes/phing/types/selectors/modifiedselector/Comparator.php
  classes/phing/types/selectors/modifiedselector/EqualComparator.php
  classes/phing/types/selectors/modifiedselector/HashfileAlgorithm.php
  classes/phing/types/selectors/modifiedselector/LastModifiedAlgorithm.php
  classes/phing/types/selectors/modifiedselector/ModifiedSelector.php
  classes/phing/types/selectors/modifiedselector/PropertiesfileCache.php
  etc/phing-grammar.rng
  test/classes/phing/types/selectors/ModifiedSelectorTest.php
  test/etc/types/selectors/ModifiedSelectorTest.xml
Labels: core, enhancement
