Repository phingofficial/phing, pull requests merged in 2020-06, with the labels that each got.

#1346 Removed PhpCodeSnifferTask
  classes/phing/tasks/defaults.properties
  classes/phing/tasks/ext/PhpCodeSnifferTask.php
  classes/phing/tasks/ext/PhpCodeSnifferTaskFormatterElement.php
  classes/phing/tasks/ext/phpcs/PhpCodeSnifferTaskWrapper.php
  classes/phing/tasks/ext/phpcs/ReportsPhingRemoveFromCache.php
  composer.lock
  test/classes/phing/tasks/ext/PhpCodeSnifferTaskTest.php
  test/etc/tasks/ext/phpcs/build.xml
Labels: cleanup, ext tasks

#1350 [PatternSet] Added missing test.
  test/classes/phing/types/PatternSetTest.php
Labels: added tests, core, system tasks

#591 MkdirTask behaves the same as "mkdir" Linux command and respects POSIX ACL
  .travis.yml
  UPGRADING.md
  classes/phing/system/io/FileSystem.php
  classes/phing/system/io/PhingFile.php
  classes/phing/tasks/system/MkdirTask.php
  test/classes/phing/tasks/system/MkdirTaskTest.php
  test/etc/tasks/system/ChmodTaskTest.xml
  test/etc/tasks/system/MkdirTaskTest.xml
Labels: enhancement
