Repository phingofficial/phing, pull requests merged in 2020-10, with the labels that each got.

#1412 Updated dependencies
  composer.lock
Labels: core

#1413 Fixed Windows codepage setting for utf8 beta.
  classes/phing/system/io/WindowsFileSystem.php
Labels: core, defect

#1414 Added GITHub action workflow.
  .github/workflows/build.yml
  test/build.xml
  test/classes/phing/types/selectors/PosixPermissionsSelectorTest.php
  test/etc/tasks/system/phing.topleveltest.xml
  test/phpunit-sparse.xml
  test/phpunit.xml
Labels: core

#1396 Fix Support for Nested Exec Env Tag - Fixes #1395
  classes/phing/tasks/system/ExecTask.php
  test/classes/phing/tasks/system/ExecTaskTest.php
  test/etc/tasks/system/ExecTest.xml
Labels: needs discussion, needs tests

#1419 Fixed env handling for windows
  classes/phing/tasks/system/ExecTask.php
  test/classes/phing/tasks/system/ExecTaskTest.php
  test/etc/tasks/system/ExecTest.xml
Labels: defect, system tasks

#1421 Fix ini parser must ignore ini sections
  classes/phing/system/io/IniFileParser.php
  test/classes/phing/system/io/IniFileParserTest.php
Labels: defect
