Repository phingofficial/phing, pull requests merged in 2021-03, with the labels that each got.

#1544 Fix "depends on" in target list
  src/Phing/Phing.php
  src/Phing/Target.php
Labels: core, defect, refactor

#1545 Remove currentTimeMillis
  src/Phing/Listener/DefaultLogger.php
  src/Phing/Listener/JsonLogger.php
  src/Phing/Listener/ProfileLogger.php
  src/Phing/Listener/ProgressLogger.php
  src/Phing/Listener/TargetLogger.php
  src/Phing/Listener/XmlLogger.php
  src/Phing/Phing.php
  src/Phing/Task/System/RecorderEntry.php
  src/Phing/Task/System/TouchTask.php
  tests/Phing/PhingTest.php
Labels: cleanup, core

#1554 Add days and hours to `DefaultLogger::formatTime` method
  .github/workflows/build.yml
  UPGRADING.md
  src/Phing/Listener/DefaultLogger.php
  tests/Phing/Listener/DefaultLoggerTest.php
  tests/Phing/Listener/SilentLoggerTest.php
  tests/Phing/Listener/TimestampedLoggerTest.php
Labels: enhancement

#1555 Updated PEAR\Exception -> composer update
  composer.lock
Labels: PHP compat, cleanup, core

#1556 [core] Removed deprecated NullPointerException.php
  composer.lock
  custom.task.properties
  src/Phing/Exception/NullPointerException.php
  src/Phing/Filter/ConcatFilter.php
  src/Phing/Filter/StripWhitespace.php
  src/Phing/Io/DirectoryScanner.php
  src/Phing/Io/File.php
  src/Phing/Io/IniFileTokenReader.php
  src/Phing/Parser/ProjectConfigurator.php
  src/Phing/Task/System/AppendTask.php
  src/Phing/Task/System/ApplyTask.php
  src/Phing/Task/System/Dirname.php
  src/Phing/Task/System/ExecTask.php
  src/Phing/Task/System/PropertyTask.php
  src/Phing/Task/System/ReflexiveTask.php
  src/Phing/Task/System/TruncateTask.php
  src/Phing/Type/AbstractFileSet.php
  src/Phing/Type/FileList.php
  src/Phing/Type/Path.php
Labels: cleanup, core, refactor

#1557 [Logger] Fixed StatisticsReport
  src/Phing/Listener/AnsiColorLogger.php
  src/Phing/Listener/DefaultLogger.php
  src/Phing/Listener/JsonLogger.php
  src/Phing/Listener/ProfileLogger.php
  src/Phing/Listener/ProgressLogger.php
  src/Phing/Listener/TargetLogger.php
  src/Phing/Listener/TimestampedLogger.php
  src/Phing/Listener/XmlLogger.php
  src/Phing/Util/ProjectTimerMap.php
  src/Phing/Util/StatisticsReport.php
  tests/Phing/Listener/StatisticsListenerTest.php
Labels: cleanup, core, defect, enhancement

#1558 [core]Moved Timer function to DefaultClock
  src/Phing/Phing.php
  src/Phing/Util/DefaultClock.php
  src/Phing/Util/Timer.php
  tests/Phing/PhingTest.php
  tests/Phing/Task/System/SleepTaskTest.php
  tests/Phing/Util/DefaultClockTest.php
Labels: cleanup, core, refactor

#1559 [core] Removed unused exception classes
  src/Phing/Exception/FileNotFoundException.php
  src/Phing/Exception/SecurityException.php
Labels: cleanup, core

#1562 Add comment in test to prevent php8.1 compat issue
  tests/etc/tasks/ext/pdepend/test.php
Labels: PHP compat, dependencies, ext tasks

#1563 [core] PHP compat issues
  src/Phing/Io/BufferedReader.php
  src/Phing/Io/File.php
  src/Phing/Io/IniFileParser.php
  src/Phing/Task/System/Pdo/DefaultPDOQuerySplitter.php
  src/Phing/Task/System/Pdo/PDOSQLExecTask.php
  src/Phing/Util/StringHelper.php
  tests/Phing/Task/Optional/PDODelimitersTest.php
  tests/Phing/Task/Optional/PHPMDTaskTest.php
Labels: PHP compat, dependencies, ext tasks
