Repository phingofficial/phing, pull requests merged in 2021-04, with the labels that each got.

#1564 [FileUtils] split up long method
  src/Phing/Io/FileUtils.php
Labels: cleanup, core, scrutinizer

#1569 removed some more annotations
  tests/Phing/Input/ConsoleInputHandlerTest.php
  tests/Phing/Input/NoInteractionInputHandlerTest.php
  tests/Phing/Io/FileParserFactoryTest.php
  tests/Phing/Io/IniFileParserTest.php
  tests/Phing/Io/YamlFileParserTest.php
  tests/Phing/Listener/DefaultLoggerTest.php
  tests/Phing/Listener/MonologListenerTest.php
  tests/Phing/Listener/SilentLoggerTest.php
  tests/Phing/Listener/StatisticsListenerTest.php
  tests/Phing/Listener/TimestampedLoggerTest.php
  tests/Phing/PropertyHelperTest.php
  tests/Phing/Task/Optional/ArgTest.php
  tests/Phing/Task/Optional/ComposerTaskTest.php
  tests/Phing/Task/Optional/IniFileTaskTest.php
  tests/Phing/Task/Optional/PHPStan/PHPStanAnalyseCommandBuilderTest.php
  tests/Phing/Task/Optional/PHPStan/PHPStanCommandBuilderFactoryTest.php
  tests/Phing/Task/Optional/PHPStan/PHPStanCommandBuilderTest.php
  tests/Phing/Task/Optional/PHPStan/PHPStanHelpCommandBuilderTest.php
  tests/Phing/Task/Optional/PHPStan/PHPStanListCommandBuilderTest.php
  tests/Phing/Task/Optional/PHPStan/PHPStanTaskTest.php
  tests/Phing/Task/Optional/PHPStan/PHPStanTaskUnitTest.php
  tests/Phing/Task/Optional/Sass/SassCompilerTest.php
  tests/Phing/Task/Optional/Sass/SassTaskAcceptanceTest.php
  tests/Phing/Task/Optional/Sass/SassTaskCompilerFactoryTest.php
  tests/Phing/Task/Optional/Sass/SassTaskUnitTest.php
  tests/Phing/Task/Optional/Sass/ScssPhpCompilerTest.php
  tests/Phing/Task/Optional/SymfonyConsoleTest.php
  tests/Phing/Task/System/TaskdefTaskTest.php
  tests/Phing/Type/ExcludesNameEntryTest.php
  tests/Phing/Type/FileListTest.php
  tests/Phing/Type/TaskdefForCopyTest.php
  tests/Phing/Util/SizeHelperTest.php
Labels: cleanup, core, scrutinizer

#1572 [core] Updated deps
  composer.lock
  custom.task.properties
Labels: core, dependencies

#1573 [core] Updated Deps - added funding to composer
  composer.json
  composer.lock
Labels: core, dependencies

#1574 [core] Fixed slack url and added security advisor dependency
  README.md
  composer.json
  composer.lock
Labels: core

#1575 [XmlLintTask] Added error logs.
  build/build-file-linter.xml
  composer.json
  composer.lock
  etc/default.tasks.properties
  src/Phing/Task/System/XmlLintTask.php
  tests/Phing/Task/System/XmlLintTaskTest.php
  tests/etc/tasks/system/XmlLintTaskTest.xml
Labels: added tests, enhancement, system tasks

#1576 [core] Scrutinizer issue fixes
  tests/Phing/Task/Optional/HttpGetTaskTest.php
Labels: core, scrutinizer

#1577 Scrutinizer issue fixes
  src/Phing/PropertyHelper.php
Labels: core, scrutinizer

#1578 Scrutinizer issue fixes
  src/Phing/Type/PatternSet.php
  tests/Phing/Type/PatternSetTest.php
Labels: core, scrutinizer

#1579 Scrutinizer issue fixes
  src/Phing/Task/System/TouchTask.php
  tests/Phing/Task/System/TouchTaskTest.php
Labels: core, scrutinizer, system tasks

#1580 Scrutinizer issue fixes
  src/Phing/ComponentHelper.php
  src/Phing/Project.php
  src/Phing/PropertyHelper.php
  tests/Phing/Io/DirectoryScannerTest.php
  tests/Phing/Support/BuildFileTest.php
  tests/Phing/Task/System/AppendTaskTest.php
Labels: core, scrutinizer

#1581 Scrutinizer issue fixes
  src/Phing/Phing.php
  src/Phing/Task/System/AdhocTask.php
  src/Phing/Task/System/AdhocTaskdefTask.php
  src/Phing/Task/System/AdhocTypedefTask.php
  src/Phing/Task/System/AppendTask.php
  src/Phing/Task/System/ApplyTask.php
  src/Phing/Task/System/Basename.php
  src/Phing/Task/System/BlockForTask.php
  src/Phing/Task/System/CaseTask.php
  src/Phing/Task/System/ChownTask.php
  src/Phing/Task/System/ConditionTask.php
  src/Phing/Task/System/SleepTask.php
  src/Phing/Task/System/TaskdefTask.php
  src/Phing/Task/System/ThrowTask.php
  src/Phing/Task/System/TruncateTask.php
  src/Phing/Task/System/VersionTask.php
Labels: core, scrutinizer

#1583 Use constant for buildfile name
  src/Phing/Task/System/PhingTask.php
Labels: cleanup

#1586 [Location] Added test
  src/Phing/Parser/Location.php
  tests/Phing/Parser/LocationTest.php
Labels: added tests, cleanup, core

#1588 [core] Fixed ExtendedFileStream register wrapper
  src/Phing/Io/ExtendedFileStream.php
Labels: core, defect

#1589 [PharPackageTask] Added attributes to test build
  tests/etc/tasks/ext/pharpackage/build.xml
Labels: added tests, system tasks

#1590 [core] Added openssl and phar.readonly to pipeline
  .github/workflows/build.yml
Labels: added tests, cleanup, core

#1591 [XmlLogger] cleanup
  src/Phing/Listener/XmlLogger.php
Labels: cleanup, core, scrutinizer

#1592 [core] Added additional tests
  tests/Phing/Task/System/PharPackageTaskTest.php
  tests/Phing/Task/System/ReplaceRegexpTaskTest.php
  tests/Phing/Task/System/SwitchTaskTest.php
  tests/Phing/Task/System/WarnTaskTest.php
  tests/etc/tasks/ext/pdepend/build.xml
  tests/etc/tasks/ext/phpcpd/build.xml
  tests/etc/tasks/ext/phpcs/build.xml
  tests/etc/tasks/ext/phplint/build.xml
  tests/etc/tasks/ext/phploc/build.xml
  tests/etc/tasks/ext/phpmd/build.xml
  tests/etc/tasks/system/ReplaceRegexpTaskTest.xml
  tests/etc/tasks/system/SwitchTest.xml
  tests/etc/tasks/system/WarnTest.xml
  tests/etc/tasks/system/pharpackage/build.xml
Labels: added tests, cleanup, core
